services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./notebooks:/workspace/notebooks
      - ./images:/workspace/images
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
        - 8888:8888
    entrypoint: jupyter lab --ip 0.0.0.0 --port=8888 --no-browser --allow-root